### ISSUE TITLE
Ask some questions with an open mind

### ISSUE THREAD

**Issue by 0xNaixi** [sevenlabs-hq/carbon#100]
Be humble and ask for advice.
1:If I want to listen to all the behavior of a account, and if the account is a pump transaction, pass it through the pumpDecoder (process it like the example), and if it's some other instruction, process the full transaction myself, is that what I should do? I'm a bit unsure how to go about implementing this after looking at the code closely.
2: If I want to get the transaction information in real time, should I set metrics_flush_interval to 0?
`.metrics_flush_interval(0)`
3: Also, is there a donation address for this project?

**Comment by KellianDev** [comment]
Thank you for your questions! I've tagged this as a "good first issue" to make it easier for others to dive in and start using the framework.

1. Yes, you typically use separate pipes for different instruction types. If you're working with multiple programs or types of instructions, you'll want a dedicated decoder and processor for each. We have a bunch of decoder crates for ecosystem programs, but let me know if some are lacking we'll consider adding them. You can also use the CLI to generate a decoder implementation from an Anchor IDL. For example:

```rust
carbon_core::pipeline::Pipeline::builder()
    .datasource(yellowstone_grpc)
    .instruction(PumpfunDecoder, PumpfunInstructionProcessor)
    .instruction(RaydiumAmmV4Decoder, RaydiumInstructionProcessor)
    .instruction(MyProgramDecoder, MyProgramInstructionProcessor)
```

If you're looking to catch unparsed instructions and handle them differently, you could use a no-op decoder or use a transaction pipe and iterate through instructions manually, but for most use cases, it should not be necessary. If you think it is, give me more context and I'll write a quick example for this.

2. The `metrics_flush_interval` setting is only for monitoring purposes. Setting it to 0 won’t affect real-time transaction information but could impact how metrics are aggregated and displayed - actually, it should never be set to zero for performance reasons. Data in Carbon isn't slowed by any setting at any point, it just goes from datasource to pipes as fast as the datasource allows. 

3. Thank you for asking! Donations are greatly appreciated. Here’s the address:
`carbFWQhgpxBstHefDcj4viA7Pp82BhEm5FZjZ8HF9w`
I’ll also add this to the README for visibility.

**Comment by 0xNaixi** [comment]
I'll tell you what I need and what I'm thinking: to listen to some accounts to see what the other side is buying and selling. It's very convenient for a pump program, but it would be very complicated to parse the transactions if it's through another swap.
For example, there are raydium pools, meteora pools, orca pools etc. Some programs even have different instructions to handle transactions. It would be cumbersome to have a dedicated decoder and processor for each of these.
So my goal is: first parse the event through the pump decoder, if the parse fails then get the full transaction, I can get a rough result of the transaction through the account before and after sol changes and token changes. This will save a lot of problems.

In addition, have sent a small amount of sol, although not much, but also a heart, if the follow-up money, will continue to donate. This is a great code for the project. Much appreciated.

**Comment by KellianDev** [comment]
Thank you!

This should fit your usecase:
```rs
use async_trait::async_trait;
use carbon_core::{
    error::CarbonResult, instruction_decoder_collection, metrics::MetricsCollection,
    processor::Processor, instruction::InstructionDecoder, transaction::TransactionProcessorInputType,
    InstructionType
};
// must have serde installed

#[derive(Debug, Clone, Serialize, Deserialize, Eq, PartialEq, Hash, InstructionType)]
pub enum IxData {
    Undecoded(Vec<u8>),
}
pub struct NoopDecoder;
impl<'a> carbon_core::instruction::InstructionDecoder<'a> for NoopDecoder {
    type InstructionType = IxData;

    fn decode_instruction(
        &self,
        instruction: &solana_sdk::instruction::Instruction,
    ) -> Option<carbon_core::instruction::DecodedInstruction<Self::InstructionType>> {
        Some(carbon_core::instruction::DecodedInstruction {
            program_id: instruction.program_id.clone(),
            accounts: instruction.accounts.clone(),
            data: IxData::Undecoded(instruction.data.clone()),
        })
    }
}

instruction_decoder_collection!(
    AllInstructions, AllInstructionsType, AllPrograms,
    Undecoded => NoopDecoder => IxData
);

pub struct TransactionProcessor;
#[async_trait]
impl Processor for TransactionProcessor {
    type InputType = TransactionProcessorInputType<AllInstructions>;

    async fn process(
        &mut self,
        update: Self::InputType,
        _metrics: Arc<MetricsCollection>,
    ) -> CarbonResult<()> {
        let (metadata, instructions, _) = update;

        if instructions
            .iter()
            .any(|(ix_metadata, ix)| ix.program_id.eq(/* pumpfun program_id*/))
        {
            return Ok(());
        }

        // do what you need to do: metadata.meta.pre_balances, metadata.meta.post_balances, metadata.meta.pre_token_balances, metadata.meta.post_token_balances

        Ok(())
    }
}
```

Having to implement this custom is not ideal. Will probably build one implementation at the framework level so this can be imported directly from core.

Your pipeline (must be using 0.3.0 for the transaction pipe):
```rs
carbon_core::pipeline::Pipeline::builder()
        .datasource(yellowstone_grpc)
        .instruction(PumpfunDecoder, PumpfunInstructionProcessor)
        .transaction(TransactionProcessor, None)
        .shutdown_strategy(carbon_core::pipeline::ShutdownStrategy::Immediate)
        .build()?
        .run()
        .await?;
```
