### ISSUE TITLE
Failed to subscribe

### ISSUE THREAD

**Issue by sondotpin** [sevenlabs-hq/carbon#102]
```[2024-11-28T18:20:13Z ERROR carbon_yellowstone_grpc_datasource] Failed to subscribe: TonicStatus(Status { code: Unknown, message: "h2 protocol error: http2 error", source: Some(tonic::transport::Error(Transport, hyper::Error(Http2, Error { kind: GoAway(b"", FRAME_SIZE_ERROR, Library) }))) })```

<img width="1788" alt="Screen Shot 2024-11-29 at 01 22 18" src="https://github.com/user-attachments/assets/9f841350-76b0-4421-9d32-b2a55ee5dcf9">

**Comment by KellianDev** [comment]
resolved in dms, was using the wrong url.
for public record, a helius geyser-enhanced ws url cannot be used in a yellowstone grpc datasource.
for a helius geyser-enhanced ws, use our helius atlas ws datasource.
