### ISSUE TITLE
Can you add the full transaction information to the InputType?

### ISSUE THREAD

**Issue by 0xNaixi** [sevenlabs-hq/carbon#105]
If you customize the processing of a transaction by instruction or transaction, there may be additional data that you want to get, such as accountKeys, but there is currently no way to get the entire transaction data, which prevents you from making certain judgments.

**Comment by KellianDev** [comment]
thank you for your feedback. we heard this feedback from multiple devs, so it will be added with v0.4.0 end of week along with a few other improvements

**Comment by nishuzumi** [comment]
That is important

**Comment by KellianDev** [comment]
just updating everyone on this, we have more features coming in v0.4.0 so it's being delayed to middle of next week (around 18th of Dec)
