### ISSUE TITLE
Support Raydium Liquidity Pool V4

### ISSUE THREAD

**Issue by iondex** [sevenlabs-hq/carbon#78]
Hi! I noticed that the Raydium Liquidity Pool V4 (675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8) decoding is not supported in Carbon. However, there is no IDL for this program either. As this program is widely used, could you please provide support for this program? Thank you!

**Comment by ilyxabatko** [comment]
Hey, @iondex! Actually, we have a [decoder create](https://crates.io/crates/carbon-raydium-amm-v4-decoder) for this program. 

An IDL can be found on [Solana FM](https://solana.fm/address/675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8/transactions?cluster=mainnet-alpha)

**Comment by siyangyuandegit** [comment]
hi will we support other launage？ like python ？

**Comment by iondex** [comment]
> Hey, @iondex! Actually, we have a [decoder crate](https://crates.io/crates/carbon-raydium-amm-v4-decoder) for this program.
> 
> An IDL can be found on [Solana FM](https://solana.fm/address/675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8/transactions?cluster=mainnet-alpha)

Will check it out. Thank you.

**Comment by quangthiennd15** [comment]
Hello @KellianDev . I want to get the exact amout out data when swapping to raydium
