### ISSUE TITLE
Raydium decoder crate doesn't work

### ISSUE THREAD

**Issue by passingBySol** [sevenlabs-hq/carbon#81]
i'm really impressed with this project! i strongly believe that open-source initiatives like this will become fundamental building blocks of the solana ecosystem, similar to yellowstone-grpc.

while testing, I discovered that the raydium-amm-v4 decoder isn't functioning correctly. specifically, i was unable to decode account updates or instructions properly.

upon investigation, i found that the instruction discriminators are incorrect. given that this is a solana native program, the current instruction discriminators appear unusually long. additionally, there are some inaccuracies in the instruction arguments.

as for now successfully implemented fixes for:
- swap instructions
- initialize2 (pool creation) instructions

would you be open to a pull request with my changes?

**Comment by quangthiennd15** [comment]
Hello @passingBySol  @KellianDev. I want to get the exact amout out data when swapping to raydium
