### ISSUE TITLE
More detailed event

### ISSUE THREAD

**Issue by 0xNaixi** [sevenlabs-hq/carbon#99]
A decoder such as carbon-pumpfun-decoder that displays the signature of a transaction in an event for easy lookup.

**Comment by KellianDev** [comment]
Check the [InstructionMetadata](https://github.com/sevenlabs-hq/carbon/blob/35a93f061a27019b035bcefabd1b9c9478356226/crates/core/src/instruction.rs#L35) and [TransactionMetadata](https://github.com/sevenlabs-hq/carbon/blob/35a93f061a27019b035bcefabd1b9c9478356226/crates/core/src/transaction.rs#L44) types that you have access to inside [InstructionProcessorInputType](https://github.com/sevenlabs-hq/carbon/blob/35a93f061a27019b035bcefabd1b9c9478356226/crates/core/src/instruction.rs#L86).

Here is a modified version of the pump fun example's instruction processor that uses the context given by the framework to get the signature.
```rs
#[async_trait]
impl Processor for PumpfunInstructionProcessor {
    type InputType = InstructionProcessorInputType<PumpfunInstruction>;

    async fn process(
        &mut self,
        data: Self::InputType,
        _metrics: Arc<MetricsCollection>,
    ) -> CarbonResult<()> {
        let (metadata, decoded_instruction, _) = data;

        let pumpfun_instruction: PumpfunInstruction = decoded_instruction.data;

        let signature = metadata.transaction_metadata.signature;

        match pumpfun_instruction {
            PumpfunInstruction::CreateEvent(create_event) => {
                println!("\nNew token created: {:#?}", create_event);
            }
            PumpfunInstruction::TradeEvent(trade_event) => {
                if trade_event.sol_amount > 10 * LAMPORTS_PER_SOL {
                    println!("\nBig trade occured: {:#?}", trade_event);
                }
            }
            PumpfunInstruction::CompleteEvent(complete_event) => {
                println!("\nBonded: {:#?}", complete_event);
            }
            _ => {}
        };

        Ok(())
    }
}
```
